name: laknat

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Ngrok
        run: npm install -g ngrok
      - name: Connect Ngrok.
        run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
